name: Docker Image CI

on:
    push:
        tags:
            - v*.*.*

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - id: set-tag-name-into-env
              run: echo "::set-env name=TAG_NAME::${GITHUB_REF##*/}"
            - name: Show tag name
              env:
                  TARGET_VERSION: ${{ env.TAG_NAME }}
              run: echo $TARGET_VERSION
            - name: Build the Docker image
              run: |
                  echo $TARGET_VERSION
                  docker build . --file Dockerfile --tag "${GITHUB_REPOSITORY}"
            - name: Login Docker Hub
              env:
                  DOCKER_USERNAME: ${{ github.repository_owner }}
                  DOCKER_PASSWORD: ${{ secrets.DOCKER_ACCESS_TOKEN }}
              run: echo -n "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
            - name: Publish the Docker image
              run: docker tag "${GITHUB_REPOSITORY}" "${GITHUB_REPOSITORY}":"${GITHUB_REF##*/}" && docker push "${GITHUB_REPOSITORY}"
